### ISSUE TITLE
Can't build in windows from v0.7.0

### ISSUE THREAD

**Issue by mimikun** [lusingander/cargo-selector#2]
Log:

```powershell
   Compiling cargo_metadata v0.19.1
   Compiling cargo-selector v0.7.0
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> C:\Users\dzdzb\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cargo-selector-0.7.0\src\main.rs:8:9
  |
8 |     os::unix::process::ExitStatusExt as _,
  |         ^^^^ could not find `unix` in `os`
  |
note: found an item that was configured out
 --> /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869\library\std\src\os\mod.rs:36:9
note: the item is gated here
 --> /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869\library\std\src\os\mod.rs:28:1
note: found an item that was configured out
 --> /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869\library\std\src\os\mod.rs:85:9
note: the item is gated here
 --> /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869\library\std\src\os\mod.rs:84:1

error[E0599]: no method named `signal` found for struct `ExitStatus` in the current scope
   --> C:\Users\dzdzb\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cargo-selector-0.7.0\src\main.rs:155:49
    |
155 |             } else if let Some(signal) = status.signal() {
    |                                                 ^^^^^^ method not found in `ExitStatus`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `cargo-selector` (bin "cargo-selector") due to 2 previous errors
error: failed to compile `cargo-selector v0.7.0`, intermediate artifacts can be found at `C:\Users\dzdzb\AppData\Local\Temp\cargo-installrDg3tZ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

but, can install v0.6.0.
Since https://github.com/lusingander/cargo-selector/commit/748c68df9e313d2423255897681fc6821ff2bf52, I can no longer build it, so I think that's related to it.

**Comment by lusingander** [comment]
https://github.com/lusingander/cargo-selector/releases/tag/v0.7.1
